---
- name: Install epel-release
  yum: name=epel-release state=present

- name: Install Firewalld
  yum: name=firewalld state=present

- name: Start and enable Firewalld service
  service: name=firewalld state=started enabled=yes

- name: Install SEManage
  yum: pkg=policycoreutils-python state=present
