---
- name: Install Nginx
  yum: name=nginx state=present

- name: Create directory for websites content
  file: path=/websites state=directory mode=0755

- name: Copy Nginx configuration
  template: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify: Restart Nginx

- name: Copy Nginx configuration for wordpress
  template: src=default.conf dest=/etc/nginx/conf.d/{{ server_hostname }}.conf
  notify: Restart Nginx

- name: Create Firewalld rule for Nginx - http
  firewalld: service=http permanent=true state=enabled immediate=yes
  ignore_errors: yes

- name: Start and enable Nginx service
  service: name=nginx state=started enabled=yes

- name: Set up seboolean to allow Nginx access to remote DB
  seboolean: name=httpd_can_network_connect_db state=yes persistent=yes
