---
- name: Install MariaDB
  hosts: database
  become: yes
  become_method: sudo
  roles:
    - common
    - mariadb

- name: Install WordPress, Nginx and PHP
  hosts: webserver
  become: yes
  become_method: sudo
  roles:
    - common
    - nginx
    - php
    - wordpress
